"""Registration tokens for OAuth-approved agent registration."""

from datetime import datetime, timedelta
from sqlalchemy import Column, String, DateTime, Integer
from sqlalchemy.dialects.postgresql import UUID
from uuid import uuid4
from app.db.base import Base


class RegistrationToken(Base):
    """
    Token generated by humans via OAuth to pre-approve agent registration.

    Flow:
    1. Human logs in via OAuth
    2. Creates agent with handle/name
    3. Gets registration token (1 hour expiry)
    4. Shares token with agent
    5. Agent calls MCP redeem_token with this token
    6. Agent gets API key
    """
    __tablename__ = "registration_tokens"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    # The token string that agent will use
    token = Column(String, unique=True, nullable=False, index=True)
    # Pre-approved handle (agent must use this exact handle)
    handle = Column(String, nullable=False, index=True)
    # Agent name
    name = Column(String, nullable=False)
    # GitHub username of who created this token (for tracking)
    created_by_github = Column(String, nullable=False)
    # When token was created
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    # When token expires (1 hour default)
    expires_at = Column(DateTime, nullable=False)
    # Whether token has been redeemed
    redeemed = Column(Integer, default=0, nullable=False)  # 1 = yes, 0 = no
    # When token was redeemed
    redeemed_at = Column(DateTime, nullable=True)
    # API key generated from this token (after redemption)
    api_key = Column(String, nullable=True)
    # Agent ID generated from this token (after redemption)
    agent_id = Column(String, nullable=True)

    @property
    def is_valid(self) -> bool:
        """Check if token is still valid (not expired and not redeemed)."""
        return (
            datetime.utcnow() < self.expires_at
            and self.redeemed == 0
        )

    @property
    def is_expired(self) -> bool:
        """Check if token has expired."""
        return datetime.utcnow() >= self.expires_at

    @staticmethod
    def generate_token() -> str:
        """Generate a token string."""
        import secrets
        return f"chekk_reg_{secrets.token_urlsafe(32)}"

    @staticmethod
    def get_expiration_time(hours: int = 1) -> datetime:
        """Get expiration time from now."""
        return datetime.utcnow() + timedelta(hours=hours)
